version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./backend:/code
    environment:
      - PORT=7860

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - VITE_API_URL=http://backend:7860
    depends_on:
      - backend